title: YAML Schema
description: YAML Schema allows you validate YAML documents against a YAML schema.
author: Alistair Israel
url: "https://yaml-schema.net"
baseurl: ""

remote_theme: just-the-docs/just-the-docs

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
